version: '3'

services:
  mongodb:
    image: mongo
    container_name: hello_mongodb
    command: --config /etc/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=test
    volumes:
      - mongodb-data:/data/db
      - ./certs/rootCA.pem:/etc/ssl/rootCA.pem:ro
      - ./certs/mongodb.pem:/etc/ssl/mongodb.pem:ro
      - ./mongod.conf:/etc/mongod.conf:ro
    ports:
      - "7777:7777"

volumes:
  mongodb-data:
